### ISSUE TITLE
文档链接无效

### ISSUE THREAD

**Issue by yoyo837** [hellof2e/quark-core-docs.github.io#3]
<img width="733" alt="image" src="https://github.com/hellof2e/quark-core-docs.github.io/assets/6134547/74650a67-dd72-418e-9c61-83712b4f07ca">

**Comment by sanqi-med** [comment]
我们文档的英文翻译暂时还没完成哦，https://quarkc.hellobike.com/#/zh-CN/docs/unsafehtml
